### ISSUE TITLE
Add favicon to browser

### ISSUE THREAD

**Issue by sangjunp4rk** [speed2fast/capstoneColmar#3]
Don't forget to put a favicon! This is the small icon on your browser tab. You can add `<link rel="icon" href="http://example.com/favicon.png">` to you `<head>` element. It’s a small detail but helps your website look more complete!

https://github.com/speed2fast/capstoneColmar/blob/master/index.html#L3

**Comment by speed2fast** [comment]
Added favicon to the Colmar site.
